# Generated by Django 3.2.10 on 2022-06-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='number',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
